## Section A: Data Structures & Control Structures

##### 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
nums = [10, 20, 30, 40, 50]
print('Original list:', nums)

# append
nums.append(60)
print('After append(60):', nums)

# extend
nums.extend([70, 80])
print('After extend([70, 80]):', nums)

# insert
nums.insert(1, 15)
print('After insert(1, 15):', nums)

# remove
nums.remove(30)
print('After remove(30):', nums)

# pop
popped_value = nums.pop()
print('After pop():', nums)
print('Popped value:', popped_value)

# index
sample_list = [10, 20, 30, 40, 50]
index_30 = sample_list.index(30)
print('Index of 30 in [10, 20, 30, 40, 50]:', index_30)

# count
count_10 = [10, 10, 20].count(10)
print('Count of 10 in [10, 10, 20]:', count_10)

# sort and reverse
arr = [5, 2, 9, 1]
print('Before sort:', arr)
arr.sort()
print('After sort():', arr)
arr.reverse()
print('After reverse():', arr)

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(1, 15): [10, 15, 20, 30, 40, 50, 60, 70, 80]
After remove(30): [10, 15, 20, 40, 50, 60, 70, 80]
After pop(): [10, 15, 20, 40, 50, 60, 70]
Popped value: 80
Index of 30 in [10, 20, 30, 40, 50]: 2
Count of 10 in [10, 10, 20]: 2
Before sort: [5, 2, 9, 1]
After sort(): [1, 2, 5, 9]
After reverse(): [9, 5, 2, 1]


#### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [3]:
students = ('Ram', 'Raju', 'Rangam')
print('Original tuple:', students)

# The following line is commented because it will cause an error.
# Tuples are immutable (cannot be changed).

# students[1] = 'Akash' # This will raise a TypeError
print('we cannot change the value of a tuple because it is immutable.')

Original tuple: ('Ram', 'Raju', 'Rangam')
we cannot change the value of a tuple because it is immutable.


#### 3. Create a set of integers with some duplicate values. Print the set and explain the output.


In [5]:
nums_set = {1, 2, 2, 3, 4, 4}
print('Set with duplicates removed:', nums_set)
print('Sets do not store duplicate values.Repeated elements appears only once.')

Set with duplicates removed: {1, 2, 3, 4}
Sets do not store duplicate values.Repeated elements appears only once.


#### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.


In [6]:
person = {'name': 'Trilok', 'age': 21, 'city': 'Bengaluru'}
print('Original dictionary:', person)

# Update age
person['age'] = 21

# Add new key email
person['email'] = 'abc@gmail.com'

print('Updated dictionary:', person)

Original dictionary: {'name': 'Trilok', 'age': 21, 'city': 'Bengaluru'}
Updated dictionary: {'name': 'Trilok', 'age': 21, 'city': 'Bengaluru', 'email': 'abc@gmail.com'}


#### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.


In [7]:
# Check if a person is eligible to vote age >= 18

def check_voting_eligibility(age):
    'Prints whether the person is eligible to vote based on age.'
    if age >= 18:
        print('Age:', age, '- Eligible to vote')
    else:
        print('Age:', age, '- Not eligible to vote')

# Example
age = 17
check_voting_eligibility(age)

Age: 17 - Not eligible to vote


#### 6. Given a 'marks' variable, print the grade:90 and above: 'A'
##### 75–89: 'B'
##### 50–74: 'C'
##### Below 50: 'Fail'


In [9]:
# Print grade according to marks.

def get_grade(marks):
    'Returns the grade based on marks.'
    if marks >= 90:
        return 'A'
    elif marks >= 75:
        return 'B'
    elif marks >= 50:
        return 'C'
    else:
        return 'Fail'

# Example
marks = 87
print('Marks:', marks, 'Grade:', get_grade(marks))

Marks: 87 Grade: B


#### 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [10]:
def check_number(num):
    'Checks if a number is positive and even, or zero, or negative.'
    if num > 0:
        if num % 2 == 0:
            print(num, 'is positive and even')
        else:
            print(num, 'is positive but odd')
    elif num == 0:
        print('The number is zero')
    else:
        print(num, 'is negative')

# Example
number = -5
check_number(number)

-5 is negative


## Section B: Numpy


#### 8.Create:
##### A scalar using np.array(5)
##### A 1D array with values 1 to 5
##### A 2D array (2x3) with values from 10 to 60 in steps of 10


In [11]:
# Import numpy
import numpy as np

#Create scalar, 1D array, and 2D array

# Scalar
scalar = np.array(5)
print('Scalar:', scalar)

# 1D array with values 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])
print('1D array:', arr1)

# 2D array (2x3) with values from 10 to 60 in steps of 10
arr2 = np.array([[10, 20, 30], [40, 50, 60]])
print('2D array (2x3):\n', arr2)

Scalar: 5
1D array: [1 2 3 4 5]
2D array (2x3):
 [[10 20 30]
 [40 50 60]]


#### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().


In [12]:
# 4x4 Numpy array of random integers between 0 and 100

random_array = np.random.randint(0, 100, (4, 4))
print('4x4 random array:\n', random_array)

4x4 random array:
 [[80 93 14 57]
 [41 61  3 12]
 [62 22 14 58]
 [76 38 46 10]]


#### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [13]:
#Convert 3x3 numpy array convert to pandas DataFrame

import pandas as pd

array_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

df_from_array = pd.DataFrame(array_3x3, columns=['A', 'B', 'C'])
print(df_from_array)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### Section C: Exploring Pandas


#### 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
##### Use .info(), .describe()
##### Select 'Name' and 'City' columns
##### Drop 'City' column
##### Fill any missing values in 'Salary' column with the mean



In [15]:
import pandas as pd
import numpy as np

data = {
    'Name': ['A','B','C','D','E','F','G','H','I','J'],
    'Age': [20, 22, 21, 23, 20, 22, 23, 21, 22, 20],
    'City': ['BLR', 'BLR', 'HYD', 'BLR', 'HYD', 'BLR', 'DEL', 'BLR', 'HYD', 'DEL'],
    'Salary': [30000, 25000, 27000, None, 32000, 29000, None, 31000, 33000, 28000]
}

df = pd.DataFrame(data)
print('Original DataFrame:')
print(df)

# .info()
print('\nDataFrame info:')
print(df.info())

# .describe()
print('\nDataFrame description:')
print(df.describe())

# Select Name and City columns
print('\nSelected columns (Name and City)')
print(df[['Name', 'City']])

# Drop City column
df_without_city = df.drop('City', axis=1)
print("\nDataFrame after dropping ,'City' column:")
print(df_without_city)

# Fill missing values in Salary with mean
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print('\nDataFrame after filling missing Salary values with mean:')
print(df)

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print('\nDataFrame after removing duplicates:')
print(df_no_duplicates)

Original DataFrame:
  Name  Age City   Salary
0    A   20  BLR  30000.0
1    B   22  BLR  25000.0
2    C   21  HYD  27000.0
3    D   23  BLR      NaN
4    E   20  HYD  32000.0
5    F   22  BLR  29000.0
6    G   23  DEL      NaN
7    H   21  BLR  31000.0
8    I   22  HYD  33000.0
9    J   20  DEL  28000.0

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame description:
             Age        Salary
count  10.000000      8.000000
mean   21.400000  29375.000000
std     1.173788   2669.269563
min    20.000000  25000.000000
25%    20.250000  27750.000000
50%    21.500000  29500.000000
75%    22.000000  31250.000000
max    23.